name: empylo
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^1.0.3
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  sms_autofill: ^2.3.0
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  collection: ^1.17.0
  image_picker: ^1.0.7
  http: ^1.2.1
  dio: ^5.4.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
    - family: Libre Baskerville
      fonts: 
        - asset: assets/fonts/LibreBaskervilleBold.ttf
          weight: 700
    - family: Switzer Variable
      fonts: 
        - asset: assets/fonts/SwitzerVariableSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SwitzerVariableRegular.ttf
          weight: 400
        - asset: assets/fonts/SwitzerVariableLight.ttf
          weight: 300
        - asset: assets/fonts/SwitzerVariableMedium.ttf
          weight: 500
        - asset: assets/fonts/SwitzerVariableBold.ttf
          weight: 700
        - asset: assets/fonts/SwitzerVariableLightItalic.ttf
          weight: 300
